# Generated by Django 4.2.5 on 2023-09-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hogwarts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='name',
            field=models.CharField(choices=[('GRYFFINDOR', 'GRYFFINDOR'), ('SLYTHERIN', 'SLYTHERIN'), ('HUFFLEPUFF', 'HUFFLEPUFF'), ('RAVENCLAW', 'RAVENCLAW')], max_length=100),
        ),
    ]
